on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy-data:
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action/deploy@v2
        with:
          app_name: wip-river-data-app
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
